"""add name to workouts

Revision ID: 3dac30d1b7a2
Revises: 25c461b84337
Create Date: 2026-08-07 02:32:16.105042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac30d1b7a2'
down_revision: Union[str, None] = '25c461b84337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'name')
    # ### end Alembic commands ###
